services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: chatty-server
    container_name: chatty-server
    environment:
      - NODE_ENV=production
    ports:
      - "3001:3001"
    volumes:
      - .:/app:z
