FROM node:20.10.0-alpine

ENV NODE_ENV development

WORKDIR /app

RUN --mount=type=bind,source=package.json,target=package.json \
    --mount=type=bind,source=package-lock.json,target=package-lock.json \
    --mount=type=cache,target=/root/.npm \
    npm ci

USER node

COPY . .

EXPOSE 3001

CMD ["npm", "run", "dev"]